AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys the instances
Parameters:
  EnvironmentName:
    Description: An environment name for VPC network configuration
    Type: String
    Default: UdacityInstances
  ApplicationsBucketName:
    Description: The bucket name for application bucket
    Type: String
    Default: udacity-application-bucket
  WebServerPolicies:
    Description: The policies for web server
    Type: CommaDelimitedList
  BastionHostKeyPair:
    Description: The key pair for bastion host
    Type: 'AWS::EC2::KeyPair::KeyName'
  WebserverKeyPair:
    Description: The key pair for web server
    Type: 'AWS::EC2::KeyPair::KeyName'
  DefaultPublicCidr:
    Description: Default public CIDR range.
    Type: String
    Default: 0.0.0.0/0
Resources:
  ApplicationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref ApplicationsBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  # ------------ IAM roles -----------------------------------------
  # ----------------------------------------------------------------
  BastionHostIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
  WebServerIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns: !Ref WebServerPolicies

  # ------------ IAM policies --------------------------------------
  # ----------------------------------------------------------------
  BastionHostIAMPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: BastionHostFullAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
      Roles:
        - !Ref BastionHostIAMRole
  ApplicationBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ApplicationBucket
      PolicyDocument:
        Id: ApplicationBucketPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${ApplicationBucket}/*'

  # ------------ IAM instance profile ------------------------------
  # ----------------------------------------------------------------
  BastionHostIAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref BastionHostIAMRole

  WebServerInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: WebServerIAMRole

  # ------------ Availability Zone 1a ------------------
  # ----------------------------------------------------

  # ------------ Bastion host --------------------------------------
  # ----------------------------------------------------------------
  BastionHostLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-053b0d53c279acc90
        InstanceType: t3.small
        KeyName: !Ref BastionHostKeyPair
        BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
              VolumeSize: '10'
              DeleteOnTermination: true
              VolumeType: 'gp2'
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeleteOnTermination: true
            DeviceIndex: 0
            Groups:
              - Fn::ImportValue: !Sub BastionHostSecurityGroup
        IamInstanceProfile:
          Arn: !GetAtt
            - BastionHostIAMInstanceProfile
            - Arn
        Monitoring:
          Enabled: true
      LaunchTemplateName:
        Fn::Join:
          - ''
          - - !Ref EnvironmentName
            - "-bastion-hosts-launch-template-"
            - Ref: "AWS::Region"

  BastionHost1a:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId:
            Fn::ImportValue: !Sub PublicSubnet1a
      LaunchTemplate:
        LaunchTemplateId:
            Ref: BastionHostLaunchTemplate
        Version:
            Fn::GetAtt: BastionHostLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ''
              - - !Ref EnvironmentName
                - '-bastion-host-'
                - !Select [ 0, !GetAZs '']
  # ------------ Bastion host network ------------------------------
  # ----------------------------------------------------------------
  BastionHostEIP1a:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub VPC
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ''
              - - !Ref EnvironmentName
                - '-bastion-host-elastic-ip-'
                - !Select [ 0, !GetAZs '' ]
  BastionHostEIP1aAssociation:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - BastionHost1a
      - BastionHostEIP1a
    Properties:
      InstanceId:
        Ref: BastionHost1a
      AllocationId:
        Fn::GetAtt:
          - BastionHostEIP1a
          - AllocationId
  # ------------ Availability Zone 1b ------------------
  # ----------------------------------------------------

  # ------------ Bastion host --------------------------
  # ----------------------------------------------------
  BastionHost1b:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId:
            Fn::ImportValue: !Sub PublicSubnet1b
      LaunchTemplate:
        LaunchTemplateId:
          Ref: BastionHostLaunchTemplate
        Version:
          Fn::GetAtt: BastionHostLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ''
              - - !Ref EnvironmentName
                - '-bastion-host-'
                - !Select [ 1, !GetAZs '' ]
  # ------------ Bastion host network ------------------------------
  # ----------------------------------------------------------------
  BastionHostEIP1b:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub VPC
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - ''
              - - !Ref EnvironmentName
                - '-bastion-host-elastic-ip-'
                - !Select [ 1, !GetAZs '' ]

  BastionHostEIP1bAssociation:
    Type: AWS::EC2::EIPAssociation
    DependsOn:
      - BastionHost1b
      - BastionHostEIP1b
    Properties:
      InstanceId:
        Ref: BastionHost1b
      AllocationId:
        Fn::GetAtt:
          - BastionHostEIP1b
          - AllocationId
  # ------------ Web server network --------------------------------
  # ----------------------------------------------------------------
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Web Server security group"
      GroupDescription: Allow http traffic to web server
      VpcId:
        Fn::ImportValue: !Sub VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: "Allow the inbound rule to all traffic of web server"
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Join ['', [!GetAtt BastionHost1a.PrivateIp, !Sub '/24']]
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Join ['', [!GetAtt BastionHost1b.PrivateIp, !Sub '/24']]
          Description: "Allow the inbound rule to specific traffic of web server"
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
          Description: "Allow the outbound rule to specific traffic of web server"
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          CidrIp: "0.0.0.0/0"

  # ------------ Web server --------------------------------
  # --------------------------------------------------------
  WebServerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install apache2 -y
            systemctl start apache2.service
            cd /var/www/html
            echo "it works! Udagram, Udacity" > index.html
        ImageId: ami-053b0d53c279acc90
        InstanceType: t3.small
        KeyName: !Ref WebserverKeyPair
        IamInstanceProfile:
          Arn: !GetAtt
            - WebServerInstanceProfile
            - Arn
        Monitoring:
          Enabled: true
        BlockDeviceMappings:
          - DeviceName: "/dev/sdk"
            Ebs:
              VolumeSize: '10'
              DeleteOnTermination: true
              VolumeType: 'gp2'
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            DeleteOnTermination: true
            DeviceIndex: 0
            Groups:
              - Ref: WebServerSecurityGroup
      LaunchTemplateName:
        Fn::Join:
          - ''
          - - !Ref EnvironmentName
            - "-web-server-launch-template-"
            - Ref: "AWS::Region"
  # ------------ Web server auto scaling group -------------
  # --------------------------------------------------------
  WebServerAutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub PrivateSubnet1a
        - Fn::ImportValue: !Sub PrivateSubnet1b
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      LaunchTemplate:
        LaunchTemplateId:
          Ref: WebServerLaunchTemplate
        Version:
          Fn::GetAtt: WebServerLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - Fn::ImportValue: !Sub ALBTargetGroup

  WebServerScaleUp:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref WebServerAutoscalingGroup
      AdjustmentType: ChangeInCapacity
      Cooldown: 300
      ScalingAdjustment: 1
  WebServerScaleDown:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref WebServerAutoscalingGroup
      AdjustmentType: ChangeInCapacity
      Cooldown: 300
      ScalingAdjustment: -1

  # ------------ CloudWatch monitoring ---------------------
  # --------------------------------------------------------
  CloudWatchHighCPUUsageAlert:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: 'WebServerCPUUsageHigh'
      MetricName: CPU Usage
      AlarmDescription: 'CPU usage is greater than 80% for 5 minutes'
      Namespace: 'AWS/EC2'
      Statistic: 'Average'
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '80'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: WebServerScaleUp
      Dimensions:
        - Name: 'AutoScalingGroupName'
          Value:
            Ref: WebServerAutoscalingGroup

  CloudWatchLowCPUUsageAlert:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: 'WebServerCPUUsageLow'
      AlarmDescription: 'CPU usage is less than 20% for 5 minutes'
      MetricName: CPU Usage
      Namespace: 'AWS/EC2'
      Statistic: 'Average'
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '20'
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - Ref: WebServerScaleDown
      Dimensions:
        - Name: 'AutoScalingGroupName'
          Value:
            Ref: WebServerAutoscalingGroup