AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys the instances
Parameters:
  EnvironmentName:
    Description: An environment name for VPC network configuration
    Type: String
    Default: UdacityHighAvailabilityApp
  ApplicationsBucketName:
    Description: Parameter for name of application bucket
    Type: String
    Default: application-bucket
Resources:
  # ------------ S3 Bucket ----------------------------------------
  ApplicationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketName: !Ref ApplicationsBucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # ------------ Permissions ---------------------------------------
  ApplicationBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ApplicationBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ApplicationBucket
                - /*
            Principal:
              AWS: '*'


  # ------------ Bastion ------------------------------------------

  # ------------ Web server ---------------------------------------
  WebServerLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          echo "Udacity Demo Web Server Running!" > index.html
      ImageId: ami-04a0ae173da5807d3
      AssociatePublicIpAddress: false
      SecurityGroups:
        - Fn::ImportValue: !Sub "WebServerSecurityGroup"
      InstanceType: t3.small
      InstanceMonitoring: true
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: '10'
  WebServerAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "PrivateSubnet1a"
        - Fn::ImportValue: !Sub "PrivateSubnet1b"
      LaunchConfigurationName:
          Ref: WebServerLaunchConfiguration
      MinSize: '2'
      MaxSize: '4'
      TargetGroupARNs:
        - Fn::ImportValue: !Sub "ALBTargetGroup"